name: golangci-lint

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'cmd/**'
      - 'pkg/**'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'cmd/**'
      - 'pkg/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
