name: test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'cmd/**'
      - 'pkg/**'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'cmd/**'
      - 'pkg/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: test
        run: |
          TEST_BOT_TOKEN=${{ secrets.TEST_BOT_TOKEN }} TEST_CHAT_ID=${{ secrets.TEST_CHAT_ID }} go test -race ./...
